### ISSUE TITLE
其实不需要再打一遍包

### ISSUE THREAD

**Issue by asukaminato0721** [hacksmo/mubu#186]
官网的 exe ，解压后里面有个 app.asar ，再找到对应版本的 eletron.

```sh
strings 幕布.exe | grep electron | less
```

看到 8.3.110.13-electron.0

对应 <https://releases.electronjs.org/release/v9.4.3>

所以用 electron9 app.asar 就可以了

**Comment by asukaminato0721** [comment]
https://pastebin.com/Kp0iB1Lp

for reference.

![image](https://github.com/kudoxu/mubu/assets/30024051/f130e092-0456-44e4-9ab0-6b6636901d3b)

**Comment by hacksmo** [comment]
感谢提醒，这个程序是把幕布的网页封装进了Electron，这样可以不用担心后续软件更新的问题。

感谢建议，打开了思路。
